spring:
   datasource:
      url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
      usename: ${PGUSER}
      password: ${PGPASSWORD}
   jpa:
      open-in-view: false
      hibernate:
         ddl-auto: validate